namespace AudioPack
{
    public enum ESoundType
    {
        None = -1,
        BananaBoom = 0,
        EnemyHurt = 1,
        PickUpSoul = 2,
        PickUpExp = 3,
        PickUpItem = 23,
        PistolShoot = 4,
        Heal = 5,
        ButtonClick = 6,
        PlayerDeath = 7,
        PlayerHurt = 8,
        Note = 9,
        Chest = 10,
        PoisonShare = 11,
        ExplosionBig = 12,
        ExplosionMedium = 13,
        ExplosionSmall = 14,
        PlainsTheme = 15,
        MinesTheme = 16,
        TavernTheme = 17,
        MapTheme = 18,
        AnvilUse = 19,
        RecycleAnvilUser = 20,
        VisionUse = 21,
        PortalEnter = 22,
        PortalOpen = 24,
        SniperRifleShoot = 25,
        LevelUp = 28,
        Dash = 29,
        ButtonHover = 30,
    CollectStar = 31,
    PickRegion = 32,
    RitualEnd = 33,
    RitualSoul = 34,
    DesertTheme = 35,
    }
}
